#!/bin/bash
#SBATCH --job-name=minipic
#SBATCH --nodes=1
#SBATCH --output=output
#SBATCH --error=error
#SBATCH --time=00:15:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --partition=cpu_short

set -e

# Modules

module purge
module load "gcc/13.2.0/gcc-4.8.5"
module load "cmake/3.21.4/gcc-13.2.0"
module load "python-nospack/3.12.4/gcc-11.2.0"

# Python env

if [[ -d ./venv ]]
then
    source ./venv/bin/activate
fi

# Launch the test

mini-run -g cpu-openmp
